// const baseUrl = "https://labourlance-hosted.onrender.com/api/v1";
const baseUrl = "http://10.0.2.2:5000/api/v1";
const loginUrl = "/auth/login";
const registerUrl = "/auth/register";
const logoutUrl = "/auth/logout";
const verifyOtpUrl = "/auth/verify";
const postJobUrl = "/jobs";
const getAllJobsUrl = "/jobs";
const getJobByFilterUrl = "/jobs/search";