// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHzsZHDDQyZ1iMoHyJ5iRz5iXTvn8jDqg',
    appId: '1:703497688414:web:9c902de855472162d02bcf',
    messagingSenderId: '703497688414',
    projectId: 'shrami-329b1',
    authDomain: 'shrami-329b1.firebaseapp.com',
    storageBucket: 'shrami-329b1.appspot.com',
    measurementId: 'G-F9KBTM025Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgwtUp0vMb21wn_gl25jVg2vOB7QLunX4',
    appId: '1:703497688414:android:dcb3e1c21fd999e2d02bcf',
    messagingSenderId: '703497688414',
    projectId: 'shrami-329b1',
    storageBucket: 'shrami-329b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU-Y4MawoFXqGh-EDlEGGp9NWfi3f2IdE',
    appId: '1:703497688414:ios:867baa6d5d6584b6d02bcf',
    messagingSenderId: '703497688414',
    projectId: 'shrami-329b1',
    storageBucket: 'shrami-329b1.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
